name: 'edzyaml'
description: 'A github action to pass values to yaml file'
inputs:
  file_path:
    description: 'yaml file path'
    required: true
  file_name:
    description: 'yaml file name'
    required: true
  yaml_key: 
    description: 'yaml file key to be pass'
    required: true
  yaml_value: 
    description: 'yaml file value to be pass'
    required: true
  
  
outputs:
  result:
    description: 'Value passed'
runs:
  using: 'docker'
  image: 'Dockerfile'
  # args:
  #   - ${{ inputs.file_path }}
  #   # - ${{ inputs.file_name }}
  #   - ${{ inputs.yaml_key }}
  #   - ${{ inputs.yaml_value }}

