name: custom action test
on:
  push:
    branches:
      - main

jobs:
    build:
        name: Custom action  
        runs-on: ubuntu-latest  
        steps:
        - uses: actions/checkout@v3
       
        - name: File modify
          uses: ./
          with:
            file_path: test.yaml
            yaml_key: 'spec.template.spec.containers.0.image'    
            yaml_value: welcome-app:asd45   
        
        - name: result check
          run: |
            echo "welcome to the gitaction world :)"
            pwd
            ls -la    
            cat test.yaml    